# Generated by Django 5.0.1 on 2024-02-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.CharField(choices=[('ImageViewer', 'ImageViewer'), ('TemperatureViewer', 'TemperatureViewer')], max_length=20),
        ),
    ]
