# Generated by Django 5.0.1 on 2024-02-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsApp', '0002_alter_element_element_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='content',
        ),
        migrations.AddField(
            model_name='element',
            name='arguments',
            field=models.JSONField(default=dict),
        ),
    ]
