# Generated by Django 5.0.1 on 2024-02-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsApp', '0003_remove_element_content_element_arguments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='arguments',
        ),
        migrations.AddField(
            model_name='element',
            name='ip_address',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
