# Generated by Django 5.0.1 on 2024-02-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsApp', '0004_remove_element_arguments_element_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='device',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
