# Generated by Django 5.0.1 on 2024-02-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settingsApp', '0005_element_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='device',
            new_name='device_type',
        ),
    ]
